
name: build_mac

on:
#  push:
#     tags:
#        - '*'
   push:
      branches: [master]
   pull_request:
      branches: [master]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15] #[macos-10.15, macox-11]
        include:
        - os: macos-10.15
#          INSTALL_DEPS: brew install boost lua
          CC: clang
          CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: install-packages
        run: |
            brew tap piScope/twopi
            brew install -v -s piscope/twopi/twopi 
