name: Release

on:
  release:
    types:
      - created

jobs:
  update_formula_version:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: piScope/TwoPi
          tap: piScope/homebrew-TwoPi
          formula: twopi.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.BREWRELEASETOKEN }}

  upload_bottle:
    name: Build and distribute Homebrew bottle for macOS Catalina
    runs-on: macos-10.15
    needs: [update_formula_version]
    steps:
      - uses: actions/checkout@v2
      - name: Install-dependencies1
        run: |
            brew install cmake open-mpi scalapack wget zlib netcdf hdf5 numpy scipy coreutils llvm libomp gmsh wxPython mpi4py mercurial
      - name: Install-dependencies2
        run: |
             $(brew --prefix)/opt/Python@3/bin/pip3 install six matplotlib Pillow hgapi PyOpenGL netCDF4 h5py PyPDF2 pdfrw future
      - name: Build a bottle using Homebrew
        run: |
            brew tap piScope/twopi
            brew install -v -s piscope/twopi/twopi --build-bottle --verbose hello
            brew bottle piscope/twopi/twopi
    
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.BREWRELEASETOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./twopi--${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_name: twopi-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip

  update_formula_bottle:
    name: Update the Homebrew formula again with bottle
    runs-on: ubuntu-latest
    needs: [upload_bottle]
    steps:
      - uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: piScope/TwoPi
          tap: piScope/homebrew-TwoPi
          formula: twopi.rb
          message: |
              Add bottle for twopi ${{ github.event.release.tag_name }}
              on macOS Catalina
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.BREWRELEASETOKEN }}	
