name: Release

on:
  release:
    types:
      - created

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: piScopea/TwoPi
          tap: piScope/twopi
          formula: twopi.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.BREWREASETOKEN }}