name: Release

on:
  release:
    types:
      - created
  
jobs:
  update_formula_version:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: bump-formula-pr
#        if: "!contains(github.ref, '-')" # skip prereleases (uncomment this later)
        run: |	
          echo ${{github.event.release.tag_name}}
          SRC_URL="https://github.com/piScope/TwoPi/archive/refs/tags/"${{github.event.release.tag_name}}".tar.gz"
          echo "${SRC_URL}"
          export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HB_TOKEN_SS }}
          brew tap piScope/twopi
          echo ${GITHUB_ACTOR}
          echo ${{ github.actor }}
          cd $(brew --repo piscope/twopi)	  
          git config --global user.name "${GITHUB_ACTOR}"
          git remote get-url --push origin
          git remote set-url origin https://x-access-token:${{ secrets.BREWRELEASETOKEN }}@github.com/piScope/twopi
          #brew bump-formula-pr --force --no-browse --no-audit --url "${SRC_URL}" piscope/twopi/twopi
          brew bump-formula-pr -f -d -v --no-fork --no-browse --no-audit --url "${SRC_URL}" piscope/twopi/twopi

#    steps:
#      - name: Extract version
#        id: extract-version
#        run: |
#          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
#      - uses: mislav/bump-homebrew-formula-action@v1
#        if: "!contains(github.ref, '-')" # skip prereleases
#        with:
#          formula-name: twopi
#          formula-path: twopi.rb
#          homebrew-tap: piScope/homebrew-TwoPi
#          base-branch: master
#          commit-message: |
#            {{formulaName}} {{version}}
#
#            Created by https://github.com/mislav/bump-homebrew-formula-action
#        env:
#          #COMMITTER_TOKEN: ${{ secrets.BREWRELEASETOKEN }}
#          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  upload_bottle:
#    name: Build and distribute Homebrew bottle for macOS Catalina
#    runs-on: macos-10.15
#    needs: [update_formula_version]
#    steps:
      #- name: Install-dependencies1
      #  run: |
      #      brew install cmake open-mpi scalapack wget zlib netcdf hdf5 numpy scipy coreutils llvm libomp gmsh wxPython mpi4py mercurial
      #- name: Install-dependencies2
      #  run: |
      #       $(brew --prefix)/opt/Python@3/bin/pip3 install six matplotlib Pillow hgapi PyOpenGL netCDF4 h5py PyPDF2 pdfrw future
      #- name: Build a bottle using Homebrew
      #  run: |
      #      brew tap piScope/twopi
      #      brew install -v piscope/twopi/twopi --build-bottle
      #      brew bottle piscope/twopi/twopi	    
#      - name: Extact Version String
#        run: |
#          echo "TAG_VERSION=$(echo ${{github.event.release.tag_name}} | sed 's/[^0-9.]*//g')" >> $GITHUB_ENV

#      - name: Upload the bottle to the GitHub release
#        uses: actions/upload-release-asset@v1.0.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.BREWRELEASETOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ./twopi--${{ env.TAG_VERSION }}.catalina.bottle.1.tar.gz
#          asset_name: twopi-${{ env.TAG_VERSION }}.catalina.bottle.tar.gz
#          asset_content_type: application/gzip

 